coverage:
    ignore:
        - "Helix Movie GuideTests/*"
        - "Helix Movie GuideUITests/*"
        - "Helix Movie Guide/DI/*"
        - "Helix Movie Guide/AppDelegate.swift"
        - "Helix Movie Guide/*Controller.swift"
        - "Helix Movie Guide/*Client.swift"
